### PR TITLE
oops: add Reason function to retrieve cause information

### PR DESCRIPTION
**Pull request by tacocat21**
Adding Reason function to oops and fixing oops_test

### CODE REVIEW

**Comment by jsm** [comment]
What was wrong with the test?

**Comment by jsm** [comment]
Also please update PR title

**Comment by tacocat21** [comment]
The old test was using unexported variables for some reason.

**Comment by tacocat21** [comment]
@jsm updated the pr

**Review by jsm — APPROVED** [review]

**Pull request merged**
